# Generated by Django 5.1.4 on 2025-06-21 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Связь комнаты и специального предложения',
                'verbose_name_plural': 'Связи комнат и специальных предложений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['name'], name='bookings_am_name_08efd3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_bo_check_i_3b9851_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'room'], name='bookings_bo_guest_i_5e3f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='bookings_gu_email_fd1cff_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name', 'first_name'], name='bookings_gu_last_na_8a4089_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='bookings_pa_status_e13a34_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='bookings_pa_payment_dce02a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['room', 'rating'], name='bookings_re_room_id_fb0006_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['guest', 'review_date'], name='bookings_re_guest_i_729039_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['is_active'], name='bookings_sp_is_acti_6d164b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['created_at'], name='bookings_sp_created_e3b469_idx'),
        ),
        migrations.AddField(
            model_name='roomspecialoffer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_special_offers', to='bookings.room', verbose_name='Комната'),
        ),
        migrations.AddField(
            model_name='roomspecialoffer',
            name='special_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_special_offers', to='bookings.specialoffer', verbose_name='Специальное предложение'),
        ),
        migrations.AddField(
            model_name='room',
            name='special_offers',
            field=models.ManyToManyField(blank=True, related_name='rooms', through='bookings.RoomSpecialOffer', to='bookings.specialoffer'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='bookings_ro_room_nu_a283c5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='bookings_ro_price_p_f8ba00_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_available'], name='bookings_ro_is_avai_8407bf_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'is_available'], name='bookings_ro_room_ty_921835_idx'),
        ),
        migrations.AddIndex(
            model_name='roomspecialoffer',
            index=models.Index(fields=['start_date', 'end_date'], name='bookings_ro_start_d_af8e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='roomspecialoffer',
            index=models.Index(fields=['is_active'], name='bookings_ro_is_acti_338113_idx'),
        ),
        migrations.AddIndex(
            model_name='roomspecialoffer',
            index=models.Index(fields=['discount_percentage'], name='bookings_ro_discoun_ce593d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomspecialoffer',
            constraint=models.UniqueConstraint(fields=('room', 'special_offer'), name='unique_room_special_offer'),
        ),
        migrations.AddConstraint(
            model_name='roomspecialoffer',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='valid_offer_dates'),
        ),
    ]
