# Generated by Django 5.0.6 on 2024-06-15 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room_max_occupancy_alter_booking_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='guest',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='bookings.amenity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_occupancy',
            field=models.IntegerField(),
        ),
    ]
