# Generated by Django 5.1.4 on 2025-06-21 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_files',
            field=models.FileField(blank=True, help_text='Другие документы, связанные с бронированием', null=True, upload_to='bookings/additional_files/', verbose_name='Дополнительные файлы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contract',
            field=models.FileField(blank=True, help_text='Сканированный договор бронирования', null=True, upload_to='bookings/contracts/', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='booking',
            name='receipt',
            field=models.FileField(blank=True, help_text='Квитанция об оплате', null=True, upload_to='bookings/receipts/', verbose_name='Квитанция'),
        ),
        migrations.AddField(
            model_name='guest',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Другие документы гостя', null=True, upload_to='guests/additional_docs/', verbose_name='Дополнительные документы'),
        ),
        migrations.AddField(
            model_name='guest',
            name='id_document',
            field=models.FileField(blank=True, help_text='Водительские права, военный билет и т.д.', null=True, upload_to='guests/id_documents/', verbose_name='Удостоверение личности'),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport_scan',
            field=models.FileField(blank=True, help_text='Скан или фото паспорта', null=True, upload_to='guests/passports/', verbose_name='Скан паспорта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_statement',
            field=models.FileField(blank=True, help_text='Выписка по банковскому переводу', null=True, upload_to='payments/bank_statements/', verbose_name='Банковская выписка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Скан или фото квитанции', null=True, upload_to='payments/receipts/', verbose_name='Квитанция об оплате'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_document',
            field=models.FileField(blank=True, help_text='Документ о возврате средств', null=True, upload_to='payments/refunds/', verbose_name='Документ о возврате'),
        ),
        migrations.AddField(
            model_name='room',
            name='documents',
            field=models.FileField(blank=True, help_text='Дополнительные документы (сертификаты, инструкции)', null=True, upload_to='rooms/documents/', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_plan',
            field=models.FileField(blank=True, help_text='PDF или изображение плана этажа', null=True, upload_to='rooms/floor_plans/', verbose_name='План этажа'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/photos/', verbose_name='Фото комнаты'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('contract', 'Договор'), ('receipt', 'Квитанция'), ('passport', 'Паспорт'), ('id_card', 'Удостоверение личности'), ('photo', 'Фото'), ('plan', 'План'), ('certificate', 'Сертификат'), ('statement', 'Выписка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли документ для просмотра гостями', verbose_name='Публичный доступ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_documents', to='bookings.booking', verbose_name='Бронирование')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_documents', to='bookings.guest', verbose_name='Гость')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='bookings.payment', verbose_name='Платёж')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_documents', to='bookings.room', verbose_name='Комната')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_type'], name='bookings_do_file_ty_ccd958_idx'), models.Index(fields=['is_public'], name='bookings_do_is_publ_12eb33_idx'), models.Index(fields=['uploaded_at'], name='bookings_do_uploade_5c745c_idx')],
            },
        ),
    ]
